
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat May 27 23:54:16 CEST 2023
//----------------------------------------------------

package ascendente.analisis_sintactico;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int SEQ = 18;
  public static final int DOSPUNTOS = 42;
  public static final int LIT_DECIMAL = 52;
  public static final int PCI = 45;
  public static final int GE = 36;
  public static final int SLASH = 29;
  public static final int CAP = 46;
  public static final int INT = 22;
  public static final int ARRAY = 20;
  public static final int ASTERISCO = 28;
  public static final int DELETE = 17;
  public static final int WRITE = 15;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int LT = 37;
  public static final int RECORD = 21;
  public static final int TYPE = 6;
  public static final int OR = 40;
  public static final int BOOL = 24;
  public static final int BEGIN = 3;
  public static final int IF = 9;
  public static final int SOMBRERO = 30;
  public static final int ID = 2;
  public static final int LE = 38;
  public static final int OF = 23;
  public static final int EOF = 0;
  public static final int TRUE = 54;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int LIT_STRING = 51;
  public static final int MODULO = 43;
  public static final int NULL = 53;
  public static final int OP_RESTA = 27;
  public static final int NEQ = 34;
  public static final int CCI = 47;
  public static final int EQ = 33;
  public static final int PCOMA = 48;
  public static final int REAL = 25;
  public static final int PAP = 44;
  public static final int ELSE = 11;
  public static final int PUNTO = 31;
  public static final int NL = 13;
  public static final int READ = 14;
  public static final int WHILE = 12;
  public static final int THEN = 10;
  public static final int LIT_ENTERO = 50;
  public static final int ASIGN = 32;
  public static final int END = 4;
  public static final int PROC = 8;
  public static final int STRING = 19;
  public static final int OP_SUMA = 26;
  public static final int FALSE = 55;
  public static final int GT = 35;
  public static final int VAR = 7;
  public static final int DO = 5;
}

