/* Generated By:JavaCC: Do not edit this line. ConstructorASTConstants.java */
package descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int TYPE = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int PROC = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int NL = 18;
  /** RegularExpression Id. */
  int READ = 19;
  /** RegularExpression Id. */
  int WRITE = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int DELETE = 22;
  /** RegularExpression Id. */
  int SEQ = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int ARRAY = 25;
  /** RegularExpression Id. */
  int RECORD = 26;
  /** RegularExpression Id. */
  int INT = 27;
  /** RegularExpression Id. */
  int REAL = 28;
  /** RegularExpression Id. */
  int OF = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int NULL = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int NOT = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int OP_SUMA = 37;
  /** RegularExpression Id. */
  int OP_RESTA = 38;
  /** RegularExpression Id. */
  int MODULO = 39;
  /** RegularExpression Id. */
  int ASTERISCO = 40;
  /** RegularExpression Id. */
  int SLASH = 41;
  /** RegularExpression Id. */
  int SOMBRERO = 42;
  /** RegularExpression Id. */
  int PUNTO = 43;
  /** RegularExpression Id. */
  int OP_ASIG = 44;
  /** RegularExpression Id. */
  int EQ = 45;
  /** RegularExpression Id. */
  int NEQ = 46;
  /** RegularExpression Id. */
  int GT = 47;
  /** RegularExpression Id. */
  int GE = 48;
  /** RegularExpression Id. */
  int LT = 49;
  /** RegularExpression Id. */
  int LE = 50;
  /** RegularExpression Id. */
  int DOSPUNTOS = 51;
  /** RegularExpression Id. */
  int PAP = 52;
  /** RegularExpression Id. */
  int PCI = 53;
  /** RegularExpression Id. */
  int CAP = 54;
  /** RegularExpression Id. */
  int CCI = 55;
  /** RegularExpression Id. */
  int PCOMA = 56;
  /** RegularExpression Id. */
  int COMA = 57;
  /** RegularExpression Id. */
  int LIT_ENTERO = 58;
  /** RegularExpression Id. */
  int LIT_DECIMAL = 59;
  /** RegularExpression Id. */
  int LIT_STRING = 60;
  /** RegularExpression Id. */
  int ID = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<BEGIN>",
    "<END>",
    "<DO>",
    "<TYPE>",
    "<VAR>",
    "<PROC>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<WHILE>",
    "<NL>",
    "<READ>",
    "<WRITE>",
    "<NEW>",
    "<DELETE>",
    "<SEQ>",
    "<STRING>",
    "<ARRAY>",
    "<RECORD>",
    "<INT>",
    "<REAL>",
    "<OF>",
    "<BOOL>",
    "<NULL>",
    "<TRUE>",
    "<FALSE>",
    "<AND>",
    "<NOT>",
    "<OR>",
    "\"+\"",
    "\"-\"",
    "\"%\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\".\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "<LIT_ENTERO>",
    "<LIT_DECIMAL>",
    "<LIT_STRING>",
    "<ID>",
  };

}
